### ISSUE TITLE
List of not print parts

### ISSUE THREAD

**Issue by MikeMihailov** [NiryoRobotics/niryo_one#1]
Hello!

Can you share the list of not print parts? 
Can I buy your custom electronics parts? I mean adaptor for Raspberry pi and Arduino controllers for steppers. Or maybe you can share the PCB and list of components.

**Comment by renarded** [comment]
Hi,

We plan to sell the custom electronics parts from March, 2018. 

We'll also update this repository soon with more info about schematics, list of parts, assembly guide, tutorials, etc :)

**Comment by MikeMihailov** [comment]
Thank you. I will wait for it ;) If i have understood correctly, I should wait for new stl too.

**Comment by Jean8marc** [comment]
Bonjour,
J'espère que la mise a jour des fichiers imprimables va bientôt arriver. Il me tarde de commencer.

**Comment by renarded** [comment]
Hi,

All STL files have been updated (+ tools), and we also add the complete list of materials in the BOM folder. (an assembly video tutorial will be published soon on our website)

You can now print the V 1.0 Niryo One :)
