### ISSUE TITLE
License

### ISSUE THREAD

**Issue by MikeMihailov** [NiryoRobotics/niryo_one#6]
Hello!

I have question about license. It is NonCommercial. Is it a violation of the use of a robot to automate a 3d printer, if I sell printed products?

**Comment by renarded** [comment]
Hi,

You can use Niryo One to do whatever you want (even automating a 3D printer and selling some non- Niryo One parts), but you can't sell the Niryo One 3D printed parts without talking with us first to see if and how we could work together.

**Comment by MikeMihailov** [comment]
Thank you!
