### ISSUE TITLE
Achat PBC board

### ISSUE THREAD

**Issue by martin73388** [NiryoRobotics/niryo_one#7]
Bonjour,

Quand sera t'il possible d'acheter vos custom Shield et  PCB ?
Enfin, pouvez vous donner les references de vos moteur pas à pas et celle des PCB accrochés derrière? 

Merci Beaucoup et bonne continuation dans votre projet.

**Comment by renarded** [comment]
Bonjour Martin,

Nous lancerons officiellement Niryo One ainsi que les pièces détachées courant septembre sur notre site.
Pour la référence des moteurs stepper, vous pouvez trouver un lien vers un excel Google Sheet [ici](https://github.com/NiryoRobotics/niryo_one/tree/master/BOM).

Le PCB attaché au moteur est un PCB custom que nous avons créé spécialement pour Niryo One. Vous pouvez trouver un schéma global [ici](https://github.com/NiryoRobotics/niryo_one/blob/master/Electronics/Niryo_stepper_overview.pdf). Nous donnerons plus d'infos lorsque nous ouvrirons les ventes sur notre site !
